//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoria_Atrybut
    {
        public int Id_Atrybut { get; set; }
        public int Id_Kategoria_ { get; set; }
        public int niepotrzebne { get; set; }
    
        public virtual Atrybut Atrybut { get; set; }
        public virtual Kategoria Kategoria { get; set; }
    }
}
