//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogloszenie_kategoria
    {
        public int Id_Ogloszenie { get; set; }
        public int Id_Kategoria_ { get; set; }
        public int ID { get; set; }
    
        public virtual Kategoria Kategoria { get; set; }
        public virtual Ogloszenie Ogloszenie { get; set; }
        public virtual Ogloszenie Ogloszenie1 { get; set; }
    }
}
