//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przedmiot
    {
        public Przedmiot()
        {
            this.Ogloszenie = new HashSet<Ogloszenie>();
        }
    
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public Nullable<int> Id_Kategoria { get; set; }
        public int Id_Uzytkownik { get; set; }
    
        public virtual Kategoria Kategoria { get; set; }
        public virtual ICollection<Ogloszenie> Ogloszenie { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
    }
}
